// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanThucAnNhanh.Data;

#nullable disable

namespace WebBanThucAnNhanh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260204015033_InitialDatabaseV2")]
    partial class InitialDatabaseV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Combo", b =>
                {
                    b.Property<int>("IdCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombo"));

                    b.Property<string>("ComboItemsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCombo");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.Property<int>("IdFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFastFood"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTheme")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeOfFastFood")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFastFood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdFastFood");

                    b.HasIndex("IdTheme");

                    b.HasIndex("IdTypeOfFastFood");

                    b.ToTable("FastFoods");

                    b.HasData(
                        new
                        {
                            IdFastFood = 1,
                            Description = "Burger bò ngon tuyệt vời",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "burger_bo.jpg",
                            NameFastFood = "Burger Bò",
                            Price = 50000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 2,
                            Description = "Nước ngọt giải khát",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "coca_cola.jpg",
                            NameFastFood = "Coca Cola",
                            Price = 15000m,
                            Quantity = 200,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 3,
                            Description = "Gà rán giòn rụm",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "ga_ran.jpg",
                            NameFastFood = "Gà Rán",
                            Price = 75000m,
                            Quantity = 150,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 4,
                            Description = "Trà sữa thơm ngon",
                            IdTheme = 1,
                            IdTypeOfFastFood = 2,
                            Image = "tra_sua.jpg",
                            NameFastFood = "Trà Sữa",
                            Price = 30000m,
                            Quantity = 180,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 5,
                            Description = "Khoai tây chiên giòn tan",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "khoai_tay_chien.jpg",
                            NameFastFood = "Khoai Tây Chiên",
                            Price = 25000m,
                            Quantity = 120,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 6,
                            Description = "Nước cam ép tươi mát",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "nuoc_cam_ep.jpg",
                            NameFastFood = "Nước Cam Ép",
                            Price = 20000m,
                            Quantity = 160,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 7,
                            Description = "Pizza hải sản hấp dẫn",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "pizza_hai_san.jpg",
                            NameFastFood = "Pizza Hải Sản",
                            Price = 120000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 8,
                            Description = "Sinh tố bơ béo ngậy",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "sinh_to_bo.jpg",
                            NameFastFood = "Sinh Tố Bơ",
                            Price = 35000m,
                            Quantity = 140,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 9,
                            Description = "Mì Ý sốt cà chua",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "mi_y.jpg",
                            NameFastFood = "Mì Ý",
                            Price = 80000m,
                            Quantity = 110,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 10,
                            Description = "Trà đào mát lạnh",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "tra_dao.jpg",
                            NameFastFood = "Trà Đào",
                            Price = 30000m,
                            Quantity = 170,
                            Status = true
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OrderDetail", b =>
                {
                    b.Property<int>("IdOrderDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderDetail"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdOrderDetail");

                    b.HasIndex("ComboId");

                    b.HasIndex("FastFoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Theme", b =>
                {
                    b.Property<int>("IdTheme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTheme"));

                    b.Property<string>("NameTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTheme");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            IdTheme = 1,
                            NameTheme = "Bữa sáng"
                        },
                        new
                        {
                            IdTheme = 2,
                            NameTheme = "Tiệc tùng"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.TypeOfFastFood", b =>
                {
                    b.Property<int>("IdTypeOfFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeOfFastFood"));

                    b.Property<string>("NameTypeOfFastFood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTypeOfFastFood");

                    b.ToTable("TypeOfFastFoods");

                    b.HasData(
                        new
                        {
                            IdTypeOfFastFood = 1,
                            NameTypeOfFastFood = "Đồ ăn nhanh"
                        },
                        new
                        {
                            IdTypeOfFastFood = 2,
                            NameTypeOfFastFood = "Đồ uống"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            Email = "admin@fastfood.com",
                            FullName = "Administrator",
                            Password = "202cb962ac59075b964b07152d234b70",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Status = true,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.Theme", "Theme")
                        .WithMany("FastFoods")
                        .HasForeignKey("IdTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanThucAnNhanh.Models.TypeOfFastFood", "TypeOfFastFood")
                        .WithMany("FastFoods")
                        .HasForeignKey("IdTypeOfFastFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");

                    b.Navigation("TypeOfFastFood");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("WebBanThucAnNhanh.Models.FastFood", "FastFood")
                        .WithMany()
                        .HasForeignKey("FastFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBanThucAnNhanh.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FastFood");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Theme", b =>
                {
                    b.Navigation("FastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.TypeOfFastFood", b =>
                {
                    b.Navigation("FastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
