// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanThucAnNhanh.Data;

#nullable disable

namespace WebBanThucAnNhanh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302063321_AddProductNameToOrderDetail")]
    partial class AddProductNameToOrderDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Combo", b =>
                {
                    b.Property<int>("IdCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombo"));

                    b.Property<string>("ComboItemsList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameCombo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCombo");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.Property<int>("IdFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFastFood"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTheme")
                        .HasColumnType("int");

                    b.Property<int>("IdTypeOfFastFood")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFastFood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("IdFastFood");

                    b.HasIndex("IdTheme");

                    b.HasIndex("IdTypeOfFastFood");

                    b.ToTable("FastFoods");

                    b.HasData(
                        new
                        {
                            IdFastFood = 1,
                            Description = "Burger bò ngon tuyệt vời",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "burger_bo.jpg",
                            NameFastFood = "Burger Bò",
                            Price = 50000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 2,
                            Description = "Nước ngọt giải khát",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "coca_cola.jpg",
                            NameFastFood = "Coca Cola",
                            Price = 15000m,
                            Quantity = 200,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 3,
                            Description = "Gà rán giòn rụm",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "ga_ran.jpg",
                            NameFastFood = "Gà Rán",
                            Price = 75000m,
                            Quantity = 150,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 4,
                            Description = "Trà sữa thơm ngon",
                            IdTheme = 1,
                            IdTypeOfFastFood = 2,
                            Image = "tra_sua.jpg",
                            NameFastFood = "Trà Sữa",
                            Price = 30000m,
                            Quantity = 180,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 5,
                            Description = "Khoai tây chiên giòn tan",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "khoai_tay_chien.jpg",
                            NameFastFood = "Khoai Tây Chiên",
                            Price = 25000m,
                            Quantity = 120,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 6,
                            Description = "Nước cam ép tươi mát",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "nuoc_cam_ep.jpg",
                            NameFastFood = "Nước Cam Ép",
                            Price = 20000m,
                            Quantity = 160,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 7,
                            Description = "Pizza hải sản hấp dẫn",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "pizza_hai_san.jpg",
                            NameFastFood = "Pizza Hải Sản",
                            Price = 120000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 8,
                            Description = "Sinh tố bơ béo ngậy",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "sinh_to_bo.jpg",
                            NameFastFood = "Sinh Tố Bơ",
                            Price = 35000m,
                            Quantity = 140,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 9,
                            Description = "Mì Ý sốt cà chua",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "mi_y.jpg",
                            NameFastFood = "Mì Ý",
                            Price = 80000m,
                            Quantity = 110,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 10,
                            Description = "Trà đào mát lạnh",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "tra_dao.jpg",
                            NameFastFood = "Trà Đào",
                            Price = 30000m,
                            Quantity = 170,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 11,
                            Description = "Hot dog truyền thống với xúc xích, mù tạt và tương cà",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "hotdog.png",
                            NameFastFood = "Hot Dog",
                            Price = 45000m,
                            Quantity = 120,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 12,
                            Description = "Gà viên chiên giòn rụm kèm sốt chấm đặc biệt",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "chicken_nuggets.png",
                            NameFastFood = "Gà Viên Chiên",
                            Price = 55000m,
                            Quantity = 130,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 13,
                            Description = "Salad Caesar tươi mát với rau xà lách, phô mai và sốt đặc trưng",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "salad_caesar.png",
                            NameFastFood = "Salad Caesar",
                            Price = 60000m,
                            Quantity = 90,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 14,
                            Description = "Taco nhân thịt bò xào rau củ tươi ngon kiểu Mexico",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "taco_bo.png",
                            NameFastFood = "Taco Bò",
                            Price = 65000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 15,
                            Description = "Hành tây chiên giòn vàng ươm thơm phức",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "onion_rings.png",
                            NameFastFood = "Hành Tây Chiên",
                            Price = 30000m,
                            Quantity = 150,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 16,
                            Description = "Sandwich gà nướng với rau xà lách, cà chua và phô mai",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "sandwich_ga.png",
                            NameFastFood = "Sandwich Gà",
                            Price = 55000m,
                            Quantity = 110,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 17,
                            Description = "Cánh gà chiên giòn sốt cay đậm đà",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "canh_ga.png",
                            NameFastFood = "Cánh Gà Chiên",
                            Price = 70000m,
                            Quantity = 120,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 18,
                            Description = "Matcha latte thơm ngon, vị trà xanh thanh mát",
                            IdTheme = 1,
                            IdTypeOfFastFood = 2,
                            Image = "matcha_latte.png",
                            NameFastFood = "Matcha Latte",
                            Price = 40000m,
                            Quantity = 160,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 19,
                            Description = "Cơm gà Hải Nam thơm dẻo với gà luộc mềm ngọt",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "com_ga.png",
                            NameFastFood = "Cơm Gà",
                            Price = 55000m,
                            Quantity = 100,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 20,
                            Description = "Cà phê sữa đá truyền thống Việt Nam đậm đà",
                            IdTheme = 1,
                            IdTypeOfFastFood = 2,
                            Image = "cafe_sua_da.png",
                            NameFastFood = "Cà Phê Sữa Đá",
                            Price = 25000m,
                            Quantity = 200,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 21,
                            Description = "Bánh mì thịt truyền thống Việt Nam với patê, thịt nguội và rau sống",
                            IdTheme = 1,
                            IdTypeOfFastFood = 1,
                            Image = "banh_mi_thit.jpg",
                            NameFastFood = "Bánh Mì Thịt",
                            Price = 35000m,
                            Quantity = 150,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 22,
                            Description = "Xúc xích nướng than hoa thơm lừng kèm mù tạt",
                            IdTheme = 2,
                            IdTypeOfFastFood = 1,
                            Image = "xuc_xich_nuong.jpg",
                            NameFastFood = "Xúc Xích Nướng",
                            Price = 40000m,
                            Quantity = 130,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 23,
                            Description = "Nước chanh dây tươi mát, chua ngọt tự nhiên",
                            IdTheme = 2,
                            IdTypeOfFastFood = 2,
                            Image = "nuoc_chanh_day.jpg",
                            NameFastFood = "Nước Chanh Dây",
                            Price = 25000m,
                            Quantity = 180,
                            Status = true
                        },
                        new
                        {
                            IdFastFood = 24,
                            Description = "Trà vải thanh mát, hương vải thơm ngọt tự nhiên",
                            IdTheme = 1,
                            IdTypeOfFastFood = 2,
                            Image = "tra_vai.jpg",
                            NameFastFood = "Trà Vải",
                            Price = 30000m,
                            Quantity = 160,
                            Status = true
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFoodOptionGroup", b =>
                {
                    b.Property<int>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.HasKey("FastFoodId", "OptionGroupId");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("FastFoodOptionGroups");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OptionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsMultiSelect")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OptionGroups");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OptionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdditionalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OptionGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionGroupId");

                    b.ToTable("OptionItems");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IdOrder");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OrderDetail", b =>
                {
                    b.Property<int>("IdOrderDetail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderDetail"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("int");

                    b.Property<int?>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReward")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdOrderDetail");

                    b.HasIndex("ComboId");

                    b.HasIndex("FastFoodId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Theme", b =>
                {
                    b.Property<int>("IdTheme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTheme"));

                    b.Property<string>("NameTheme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTheme");

                    b.ToTable("Themes");

                    b.HasData(
                        new
                        {
                            IdTheme = 1,
                            NameTheme = "Bữa sáng"
                        },
                        new
                        {
                            IdTheme = 2,
                            NameTheme = "Tiệc tùng"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.TypeOfFastFood", b =>
                {
                    b.Property<int>("IdTypeOfFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeOfFastFood"));

                    b.Property<string>("NameTypeOfFastFood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTypeOfFastFood");

                    b.ToTable("TypeOfFastFoods");

                    b.HasData(
                        new
                        {
                            IdTypeOfFastFood = 1,
                            NameTypeOfFastFood = "Đồ ăn nhanh"
                        },
                        new
                        {
                            IdTypeOfFastFood = 2,
                            NameTypeOfFastFood = "Đồ uống"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DrinkSpins")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodSpins")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            DrinkSpins = 0,
                            Email = "admin@fastfood.com",
                            FoodSpins = 0,
                            FullName = "Administrator",
                            Password = "202cb962ac59075b964b07152d234b70",
                            PhoneNumber = "0123456789",
                            Role = "Admin",
                            Status = true,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.UserReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("PrizeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrizeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRewards");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.WheelPrize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FastFoodId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PrizeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PrizeType")
                        .HasColumnType("int");

                    b.Property<double>("Probability")
                        .HasColumnType("float");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FastFoodId");

                    b.ToTable("WheelPrizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FastFoodId = 2,
                            IsActive = true,
                            PrizeName = "Coca Cola miễn phí",
                            PrizeType = 1,
                            Probability = 15.0,
                            RemainingQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            FastFoodId = 4,
                            IsActive = true,
                            PrizeName = "Trà Sữa miễn phí",
                            PrizeType = 1,
                            Probability = 12.0,
                            RemainingQuantity = 40
                        },
                        new
                        {
                            Id = 3,
                            FastFoodId = 6,
                            IsActive = true,
                            PrizeName = "Nước Cam Ép miễn phí",
                            PrizeType = 1,
                            Probability = 14.0,
                            RemainingQuantity = 45
                        },
                        new
                        {
                            Id = 4,
                            FastFoodId = 8,
                            IsActive = true,
                            PrizeName = "Sinh Tố Bơ miễn phí",
                            PrizeType = 1,
                            Probability = 8.0,
                            RemainingQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            FastFoodId = 10,
                            IsActive = true,
                            PrizeName = "Trà Đào miễn phí",
                            PrizeType = 1,
                            Probability = 12.0,
                            RemainingQuantity = 40
                        },
                        new
                        {
                            Id = 6,
                            FastFoodId = 18,
                            IsActive = true,
                            PrizeName = "Matcha Latte miễn phí",
                            PrizeType = 1,
                            Probability = 7.0,
                            RemainingQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            FastFoodId = 20,
                            IsActive = true,
                            PrizeName = "Cà Phê Sữa Đá miễn phí",
                            PrizeType = 1,
                            Probability = 12.0,
                            RemainingQuantity = 45
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            PrizeName = "Chúc may mắn lần sau!",
                            PrizeType = 1,
                            Probability = 20.0,
                            RemainingQuantity = 9999
                        },
                        new
                        {
                            Id = 9,
                            FastFoodId = 1,
                            IsActive = true,
                            PrizeName = "Burger Bò miễn phí",
                            PrizeType = 2,
                            Probability = 10.0,
                            RemainingQuantity = 30
                        },
                        new
                        {
                            Id = 10,
                            FastFoodId = 3,
                            IsActive = true,
                            PrizeName = "Gà Rán miễn phí",
                            PrizeType = 2,
                            Probability = 8.0,
                            RemainingQuantity = 25
                        },
                        new
                        {
                            Id = 11,
                            FastFoodId = 5,
                            IsActive = true,
                            PrizeName = "Khoai Tây Chiên miễn phí",
                            PrizeType = 2,
                            Probability = 14.0,
                            RemainingQuantity = 50
                        },
                        new
                        {
                            Id = 12,
                            FastFoodId = 7,
                            IsActive = true,
                            PrizeName = "Pizza Hải Sản miễn phí",
                            PrizeType = 2,
                            Probability = 4.0,
                            RemainingQuantity = 15
                        },
                        new
                        {
                            Id = 13,
                            FastFoodId = 11,
                            IsActive = true,
                            PrizeName = "Hot Dog miễn phí",
                            PrizeType = 2,
                            Probability = 12.0,
                            RemainingQuantity = 40
                        },
                        new
                        {
                            Id = 14,
                            FastFoodId = 12,
                            IsActive = true,
                            PrizeName = "Gà Viên Chiên miễn phí",
                            PrizeType = 2,
                            Probability = 10.0,
                            RemainingQuantity = 35
                        },
                        new
                        {
                            Id = 15,
                            FastFoodId = 16,
                            IsActive = true,
                            PrizeName = "Sandwich Gà miễn phí",
                            PrizeType = 2,
                            Probability = 10.0,
                            RemainingQuantity = 30
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            PrizeName = "Chúc may mắn lần sau!",
                            PrizeType = 2,
                            Probability = 32.0,
                            RemainingQuantity = 9999
                        });
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.Theme", "Theme")
                        .WithMany("FastFoods")
                        .HasForeignKey("IdTheme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanThucAnNhanh.Models.TypeOfFastFood", "TypeOfFastFood")
                        .WithMany("FastFoods")
                        .HasForeignKey("IdTypeOfFastFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");

                    b.Navigation("TypeOfFastFood");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFoodOptionGroup", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.FastFood", "FastFood")
                        .WithMany("FastFoodOptionGroups")
                        .HasForeignKey("FastFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanThucAnNhanh.Models.OptionGroup", "OptionGroup")
                        .WithMany()
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FastFood");

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OptionItem", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.OptionGroup", "OptionGroup")
                        .WithMany("OptionItems")
                        .HasForeignKey("OptionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OptionGroup");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("WebBanThucAnNhanh.Models.FastFood", "FastFood")
                        .WithMany()
                        .HasForeignKey("FastFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBanThucAnNhanh.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("FastFood");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.UserReward", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.WheelPrize", "WheelPrize")
                        .WithMany()
                        .HasForeignKey("PrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBanThucAnNhanh.Models.User", "User")
                        .WithMany("UserRewards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WheelPrize");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.WheelPrize", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.FastFood", "FastFood")
                        .WithMany()
                        .HasForeignKey("FastFoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FastFood");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.Navigation("FastFoodOptionGroups");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.OptionGroup", b =>
                {
                    b.Navigation("OptionItems");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.Theme", b =>
                {
                    b.Navigation("FastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.TypeOfFastFood", b =>
                {
                    b.Navigation("FastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("UserRewards");
                });
#pragma warning restore 612, 618
        }
    }
}
