// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanThucAnNhanh.Data;

#nullable disable

namespace WebBanThucAnNhanh.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120105331_fastfood_typeoffastfood")]
    partial class fastfood_typeoffastfood
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.Property<int>("IdFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFastFood"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTypeOfFastFood")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameFastFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TypeOfFastFoodIdTypeOfFastFood")
                        .HasColumnType("int");

                    b.HasKey("IdFastFood");

                    b.HasIndex("TypeOfFastFoodIdTypeOfFastFood");

                    b.ToTable("FastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.TypeOfFastFood", b =>
                {
                    b.Property<int>("IdTypeOfFastFood")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeOfFastFood"));

                    b.Property<string>("NameTypeOfFastFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTypeOfFastFood");

                    b.ToTable("TypeOfFastFoods");
                });

            modelBuilder.Entity("WebBanThucAnNhanh.Models.FastFood", b =>
                {
                    b.HasOne("WebBanThucAnNhanh.Models.TypeOfFastFood", "TypeOfFastFood")
                        .WithMany()
                        .HasForeignKey("TypeOfFastFoodIdTypeOfFastFood")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeOfFastFood");
                });
#pragma warning restore 612, 618
        }
    }
}
